# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"\x15\n\x07Request\x12\n\n\x02ts\x18\x01 \x01(\x05\"!\n\x05Video\x12\x0c\n\x04m3u8\x18\x01 \x01(\x0c\x12\n\n\x02ts\x18\x02 \x01(\x0c\"\x17\n\x06Result\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"\x15\n\x06Source\x12\x0b\n\x03uri\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa0\x01\n\x0bWorker_gRPC\x12.\n\tGetStatus\x12\x0f.worker.Request\x1a\x0e.worker.Status\"\x00\x12.\n\x08GetVideo\x12\x0e.worker.Source\x1a\x0e.worker.Result\"\x00\x30\x01\x12\x31\n\rRestreamVideo\x12\x0e.worker.Source\x1a\x0e.worker.Source\"\x00\x42\tZ\x07/go_apib\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_VIDEO = DESCRIPTOR.message_types_by_name['Video']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
_SOURCE = DESCRIPTOR.message_types_by_name['Source']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:worker.Request)
  })
_sym_db.RegisterMessage(Request)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:worker.Video)
  })
_sym_db.RegisterMessage(Video)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:worker.Result)
  })
_sym_db.RegisterMessage(Result)

Source = _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
  'DESCRIPTOR' : _SOURCE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:worker.Source)
  })
_sym_db.RegisterMessage(Source)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:worker.Status)
  })
_sym_db.RegisterMessage(Status)

_WORKER_GRPC = DESCRIPTOR.services_by_name['Worker_gRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007/go_api'
  _REQUEST._serialized_start=24
  _REQUEST._serialized_end=45
  _VIDEO._serialized_start=47
  _VIDEO._serialized_end=80
  _RESULT._serialized_start=82
  _RESULT._serialized_end=105
  _SOURCE._serialized_start=107
  _SOURCE._serialized_end=128
  _STATUS._serialized_start=130
  _STATUS._serialized_end=154
  _WORKER_GRPC._serialized_start=157
  _WORKER_GRPC._serialized_end=317
# @@protoc_insertion_point(module_scope)
